apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: fetch-scanner-v4-vuln-mappings
spec:
  description: Fetches vulnerability mappings for Scanner v4 from StackRox artifacts to be baked into the image.
  params:
  - name: TARGET_DIR
    description: Target directory relative to workspace where to save downloaded files.
    type: string
  - name: SOURCE_ARTIFACT
    description: The Trusted Artifact URI pointing to the application source code.
    type: string
  - name: ociStorage
    description: The OCI repository where the Trusted Artifacts are stored.
    type: string
  - name: ociArtifactExpiresAfter
    description: Expiration date for the trusted artifacts created in the
      OCI repository.
    type: string
  results:
  - name: SOURCE_ARTIFACT
    description: The Trusted Artifact URI pointing to the artifact with the application source code and
      additional vulnerability mappings.
    type: string
  volumes:
  - name: workdir
    emptyDir: { }
  stepTemplate:
    volumeMounts:
    - mountPath: /var/workdir
      name: workdir
  steps:
  - name: use-trusted-artifact
    image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:ff35e09ff5c89e54538b50abae241a765b2b7868f05d62c4835bebf0978f3659
    args:
    - use
    - $(params.SOURCE_ARTIFACT)=/var/workdir/source
  - name: fetch-vuln-mappings
    image: registry.access.redhat.com/ubi9-minimal:latest@sha256:3902bab19972cd054fd08b2a4e08612ae7e68861ee5d9a5cf22d828f27e2f479
    workingDir: /var/workdir/source
    script: scanner/image/scanner/download-mappings.sh "$(params.TARGET_DIR)"
  - name: create-trusted-artifact
    image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:ff35e09ff5c89e54538b50abae241a765b2b7868f05d62c4835bebf0978f3659
    args:
    - create
    - --store
    - $(params.ociStorage)
    - $(results.SOURCE_ARTIFACT.path)=/var/workdir/source
    env:
    - name: IMAGE_EXPIRES_AFTER
      value: $(params.ociArtifactExpiresAfter)
