name: auto-merge

on:
  pull_request_target:
    types:
    - labeled

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'red-hat-konflux[bot]' && github.event.label.name == 'auto-merge'
    env:
      GH_TOKEN: ${{ secrets.RHACS_BOT_GITHUB_TOKEN }}
    steps:
    - name: Approve PR
      run: |
        gh pr review ${{ github.event.pull_request.number }} --approve --body "/ok-to-test" --repo ${{ github.repository }}
